### ISSUE TITLE
Add natural log node class

### ISSUE THREAD

**Issue by olamide203** [olamide203/hyoka#10]
### is there an existing issue for this?

- [X] I have searched the existing issues

### Description

it would be great to have a natural log node class that can be used to evaluate expressions of the form `ln(x)` by the parser. a new class `NaturalLog` that extends the `TreeNode` class would be the ideal solution. 

### Use Case

```js
new Expression('ln(2)').evaluate()        // 0.6931471805....
new Expression('ln(2π)').evaluate()     // 1.83787706640....
```

**Comment by fazzaamiarso** [comment]
Hello @olamide203, can I help with this issue?

**Comment by olamide203** [comment]
yea sure, go ahead
