### ISSUE TITLE
chore: pull request template

### ISSUE THREAD

**Issue by olamide203** [olamide203/hyoka#17]
add a pull request template to the project for improved pull request description. 

for reference:
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)

**Comment by kat-kan** [comment]
Can I try working on this?
What type of info do you expect in the template?

**Comment by olamide203** [comment]
yeah sure,
The template should contain the following sections:
- a list of proposed changes.
- extra notes if applicable
- if a PR fixes an open issue, use `Closes #XX` to link the PR to the issue (this can be a comment)

**Comment by TejasSharma3014** [comment]
Can I also work on this.

**Comment by olamide203** [comment]
> Can I also work on this.

I think @kat-kan is working on this already

**Comment by kat-kan** [comment]
Yes I am. @TejasSharma3014 I'll let know if I need help
