### ISSUE TITLE
feat: add options for decimal places

### ISSUE THREAD

**Issue by whinc** [olamide203/hyoka#61]
### Description

I couldn't set the number of decimal places through only hyoka and had to do extra processing with decimal.js which requires user to install another library.

```js
const { Expression } = require('hyoka');
const Decimal = require('decimal.js');
Expression.config({
  precision: 10
});
new Decimal(new Expression('12345 + 1/3').evaluate()).toDecimalPlaces(4).toString()
```

### Use Case

I think the `evaluate()` method can support configurting decimal places with method signature`evaluate(options?: {decimalPlaces?: number})`

**Comment by olamide203** [comment]
sounds like a good addition. In addition to this, I think it would be good to have local `config` options in general, which can overwrite global config values.
```js
const { Expression } = require('hyoka');
Expression.config({
  precision: 20,
  decimalPlaces: 10 // set global default for decimal places
});

expr = new Expression('12345 + 1/3');
expr.evaluate({decimalPlaces: 4, precision: 10});  // 1234.3333
expr.evaluate() // 1234.3333333333
```

**Comment by whinc** [comment]
> sounds like a good addition. In addition to this, I think it would be good to have local `config` options in general, which can overwrite global config values.
> 
> ```js
> const { Expression } = require('hyoka');
> Expression.config({
>   precision: 20,
>   decimalPlaces: 10 // set global default for decimal places
> });
> 
> expr = new Expression('12345 + 1/3');
> expr.evaluate({decimalPlaces: 4, precision: 10});  // 1234.3333
> expr.evaluate() // 1234.3333333333
> ```
> 
> what are your thoughts on this?

Yes, i agree with you
